### ISSUE TITLE
18Ardennes: player trades in minor for 5th share in major but minor doesn't disappear

### ISSUE THREAD

**Issue by ianwilson156** [ollybh/18xx#101]
Player 2 trades in #14 for the 5th share in Be, getting the assets, but #14 doesn't close!

**Comment by ianwilson156** [comment]
Also, note there were share prices rising for fully sold but that is not a feature of this game!

**Comment by ollybh** [comment]
The minor staying open is fixed in commit 5ee6a842f.
The share price bump for sold out companies is removed in commit 7b64f8004.
