### ISSUE TITLE
18Ardennes: Cannot go over 60% holding when growing to 10-share by trading in a minor

### ISSUE THREAD

**Issue by ianwilson156** [ollybh/18xx#102]
Player 3 has grown up By to 10-share and bought 2 shares to get to 60%, but now cannot trade in #2 to get a 7th share.
Also, there are only 9 shares of By!

**Comment by ianwilson156** [comment]
It seems you can either buy shares or trade in a minor, but not both.

**Comment by ollybh** [comment]
Everything was backwards. You could buy shares to go above the 60% limit, but not exchange a minor to get there.
Fixed in commit 46a0d1034.
