### ISSUE TITLE
18Ardennes: cert limit does not rise with 10-share companies, and cert calculation is wrong

### ISSUE THREAD

**Issue by ianwilson156** [ollybh/18xx#105]
3 companies have grown up but the cert limit is still 11.
Also, the numbers don't add up properly.

**Comment by ollybh** [comment]
This is *very* untested, but the certificate limit should now increase (commit b23e8b7a7).
I think the certificate miscount would have been isssue #103, when the director's certificate was being converted to a 10% share.
Let me know if anything still seems wrong.
