### ISSUE TITLE
Not auto-passing in SR1 (minor)

### ISSUE THREAD

**Issue by ianwilson156** [ollybh/18xx#120]
After the initial auction, the program passes for three players but doesn't for player 2, even though they have no money!

**Comment by ollybh** [comment]
> After the initial auction, the program passes for three players but doesn't for player 2, even though they have no money!

Does player 2 own the GL? Technically they are allowed to sell the GL in SR1. They'd have to be insane to do this, but it's a legal move.

**Comment by ianwilson156** [comment]
Ah, perhaps it's because player 2 has the GL?
We've always played that you go directly from the end of the auction to OR1, but the rules are totally unclear on this point. Even so, there seems little point in having an SR1 since selling the GL is utterly dumb.

**Comment by ollybh** [comment]
Yeah, I agree. The game will now go straight from the initial minor company auction into the first operating round, with no intervening stock round. Fixed in commit b2d0ee4f4.
