### ISSUE TITLE
Should be able to go over 60% limit by buying market share

### ISSUE THREAD

**Issue by ianwilson156** [ollybh/18xx#125]
Player 5 has 3 shares of By, there is a 4th in the market and he has the cash, but is not given the option to buy it.

**Comment by ollybh** [comment]
I'd missed that rule. I thought that the only way you could go over a 60% holding is by exchanging a minor.

**Comment by ianwilson156** [comment]
I thought it had been implemented earlier, but I may have been confusing it with another title,

Because shares in the market depress the price at the end of an SR, this rule is necessary.

**Comment by ollybh** [comment]
Fixed in commit 4f8471bae.
