### ISSUE TITLE
18Ardennes: major not connected to new track after taking over a minor

### ISSUE THREAD

**Issue by ianwilson156** [ollybh/18xx#135]
The NL has just grown up to 10-share and taken over #9 (and taken its token in Paris). Now NL comes to lay track, but cannot lay anything east of Paris e.g. Metz, even though it is now connected! Strange.

**Comment by ianwilson156** [comment]
Once it does an upgrade, it can lay a token in Metz...

**Comment by ollybh** [comment]
Maybe a graph issue? Is this being cleared after a minor's tokens are acquired or removed from the map?

**Comment by ollybh** [comment]
https://gist.github.com/ollybh/ce7b73011dd12c8817a57bcf787ff2e3#file-hs_bobieuyh_1716997236-1-json

**Comment by ianwilson156** [comment]
Even if NL declines #9's token in Paris, it still isn't connected to Metz - it's like #9's token is still there! As above, it corrects itself by the token laying step.
