### ISSUE TITLE
18CH: mountain railway not available in Phase 4

### ISSUE THREAD

**Issue by ianwilson156** [ollybh/18xx#143]
STB is trying to build a Mt Rwy in G10 but it says 'later phase'. A 6H has been bought.

**Comment by ollybh** [comment]
I had mentioned that I hadn't tested the mountain railways much...

This was not allowing the mountain railway tile as it's a grey tile, and grey tiles aren't available until much later.

Hopefully this is fixed now.

**Comment by ianwilson156** [comment]
If you want to change the tile colour to green, that's ok - as long as you can't upgrade it!

**Comment by ianwilson156** [comment]
Seems to be ok now.
