### ISSUE TITLE
Special rules for private railway track connections from Gotthard hex (H11)

### ISSUE THREAD

**Issue by ianwilson156** [ollybh/18xx#144]
The FOB has a home hex in H11, but isn't supposed to be able to trace a broad-gauge route from there - it is only connected to the narrow-gauge part of that hex.
The program correctly rejects a narrow-gauge build in C12, but allows a broad-gauge build.
Similarly, GB can't trace a route from the narrow-gauge part of H11. It's a crossover: they are several thousand feet apart (vertically)!

**Comment by ianwilson156** [comment]
Yes, it is a bit different from 1858. And yes, a major would need to trace to the appropriate gauge of track in H11.
It may be simpler just to remove H11 as the home hex of GB and FOB - as long as the track stubs remain as they are. It would mean GB couldn't build towards Lugano before building Altdorf, but that's no hardship.

**Comment by ollybh** [comment]
I had also wondered about removing H11 from GB and FOB’s home hexes, but that wouldn't be much simpler, I'd have to change the way that stubs are handled.

I've fixed the first part of this: GB can now only trace routes from H11 using the broad gauge track and FOB can only use the metre gauge track.

I'll leave the issue open until I've stopped connections to public companies using the wrong track.

**Comment by ollybh** [comment]
The check for a public company’s connection to the right piece of track in H11 is now in place.

**Comment by ianwilson156** [comment]
Great!
