### ISSUE TITLE
18CH: mountain hex tile wrong colour (minor)

### ISSUE THREAD

**Issue by ianwilson156** [ollybh/18xx#146]
STB builds a bit of track (in D15) pointing towards a blank hexside of a mountain hex.

**Comment by ollybh** [comment]
![image](https://github.com/ollybh/18xx/assets/11144854/3eb648d0-88d6-4dc2-91db-c403e3d4a104)

**Comment by ollybh** [comment]
@ianwilson156 is this incorrect? Generally you are only forbidden from building track that points off the edge of the map, or to an impassable border.

And if you want to forbid building tracks pointing at the edges of these tiles, would this mean that you can´t place a mountain railway tile in a hex that already has more than a single connection to it?

**Comment by ianwilson156** [comment]
Mmmm. With a pre-printed red or grey tile, you're generally not allowed to point track at blank hexsides.
In this case, the hex represents a big mountain range with a (tourist) railway going up one side, so there's no real reason to stop a company pointing at another side of the mountain - it just looks wrong because the hex is grey.
I think the best solution is to change the colour of the tile. I think it should really be yellow, since it is effectively a normal build on a blank hex.

**Comment by ianwilson156** [comment]
We have other yellow tiles which don't upgrade e.g. double-dots. And you can point at their blank sides.

**Comment by ollybh** [comment]
I can change it to yellow easily enough. But you still don´t want it to be built until phase 4, right?

**Comment by ianwilson156** [comment]
Yes, not until phase 4 (the technology - rack and pinion) wasn't invented until about then. It will still seem a bit weird: a yellow tile you can't lay until the green phase.
In 1829, Francis introduced a brown tile (i.e. upgrade for a green tile) which wasn't available until the grey phase. He made it a stripy brown/grey: #166. So we should make this stripy yellow/green?

**Comment by ianwilson156** [comment]
There's also a green/brown stripy tile: 119 in 1825.

**Comment by ollybh** [comment]
I have made the tile yellow for the moment. There is support for striped tiles, but I haven´t used these before, I will have to look into the code to see how they affect placement.

**Comment by ollybh** [comment]
The tile is now green with yellow stripes.

It looks a bit weird with the stripes vertical, imho. Almost all of the games that have striped tiles have a pointy map layout, so the stripes are angled on those. I'll see if I can rotate the stripes by 30°.
![image](https://github.com/ollybh/18xx/assets/11144854/69a82184-bdbc-4844-9496-815254b4b82f)

**Comment by ollybh** [comment]
Stripes now rotated by 60° (not 30°, brain wasn't working).
![image](https://github.com/ollybh/18xx/assets/11144854/5f5a8d03-2c5f-48a4-98bb-7be7d3470bc9)

**Comment by ianwilson156** [comment]
Looks good!
