### ISSUE TITLE
[18CH] Rules update (change privates)

### ISSUE THREAD

**Issue by ianwilson156** [ollybh/18xx#148]
A rethink of the privates has changed them to the following:

Available at the beginning:
| No | Name                    | Symbol | Min bid | Face value | Income | Home city  |
| -- | ----------------------- | ------ | ------- | ---------- | ------ | ---------- |
| 1  | Nordbahn                | NB     |  55     |  70        | 14/21  | Zurich (W) |
| 2  | Nordostbahn             | NOB    |  95     | 120        | 24/36  | Zurich (E) |
| 3  | Centralbahn             | SCB    |  90     | 115        | 23/35  | Basel      |
| 4  | Vereingtebahn           | VSB    |  85     | 105        | 21/32  | St Gallen  |
| 5  | Lausanne-Fribourg-Berne | LFB    |  90     | 110        | 22/33  | Lausanne   |
| 6  | Ouest Suisse            | OS     |  65     |  80        | 16/24  | Geneve     |
| 7  | Bernische Staatsbahn    | BSB    |  80     | 100        | 20/30  | Bern       |
| 8  | Bodelibahn              | BB     |  50     |  60        | 12/18  | None       |
| 9  | Gotthardbahn            | GB     |  50     |  65        | 13/20  | None       |
| 10 | Bern-Luzern-Bahn        | BLB    |  70     |  90        | 18/27  | Luzern     |
| 11 | Emmentalbahn            | EB     |  45     |  55        | 11/17  | None       |

Available from Phase 3:
| No | Name                    | Symbol | Min bid | Face value | Income | Home city  |
| -- | ----------------------- | ------ | ------- | ---------- | ------ | ---------- |
| 12 | Alta Italia             | AFAI   | 135     | 135        | 40     | Lugano     |
| 13 | Jura neuchatelois       | JN     |  85     |  85        | 25     | None       |
| 14 | Visp-Zermatt            | VZ     |  75     |  75        | 22     | None       |

(no change to #15-18)
P1 can now start a company.

**Comment by ianwilson156** [comment]
i.e. different are P1, 6, 8, 9, 10, 12, 13 & 14.

**Comment by ollybh** [comment]
@ianwilson156 So there are now just two groups of privates like 1858. Does this mean that the second private closure round has gone too?

**Comment by ianwilson156** [comment]
No, the third tranche are the same as before.

**Comment by ollybh** [comment]
The updated private values should be active now. Let me know if anything is wrong.

**Comment by ianwilson156** [comment]
Just one small problem - P9 (GB) should have a minimum bid of 50 (not 55): 80% of 65 = 52, rounded to 50.
Otherwise looks fine.

**Comment by ianwilson156** [comment]
OTOH...  I cannot start a company with P1.
Player 1 has both P1 and P12, and the BLS is unstarted. Clicking on the charter, he just has P12 available to start it, but it should also allow P1.
I'll send you the json.

**Comment by ollybh** [comment]
> Just one small problem - P9 (GB) should have a minimum bid of 50 (not 55): 80% of 65 = 52, rounded to 50. Otherwise looks fine.

Fixed.

**Comment by ollybh** [comment]
> OTOH... I cannot start a company with P1. Player 1 has both P1 and P12, and the BLS is unstarted. Clicking on the charter, he just has P12 available to start it, but it should also allow P1. I'll send you the json.

Oops, I'd forgotten to give NB the ability needed to start a public company. Fixed now.
