### ISSUE TITLE
[1858Switzerland] Robot for two-player game

### ISSUE THREAD

**Issue by ollybh** [ollybh/18xx#149]
Rules for a two-player variant with a robot player, from @ianwilson156:

> Robot (2-player only)
> 
> Start capital is sf335 (as 3-player) and cert limit is 13. There are only four player companies – the 5th company is the State (SBB).
> 
> During stock rounds, the Robot always acts in 3rd position; it will acquire the most expensive private available (resolve ties by lowest number). It has no cash and never buys shares in Public Companies.
> 
> During operating rounds, Robot owned privates must build one of their reserved hexes each round, until all such are built. Starting with the holder of the Priority, and alternating between them, the players choose which tiles to lay. Once a private has built all its reserved hexes, it closes (merges into the SBB). If the private had a reserved slot in a city, place a SBB token there. SBB has a maximum of 5 tokens.
> 
> The SBB starts operating once a 2H train has been purchased. It operates last in an OR. The player with Priority runs it for the first OR of the set, the other player for the 2nd. It must upgrade a city in which it has a token, if possible. In the 2nd OR, it will also acquire the next new train from the Bank (resolve Phase changes normally). The SBB has no treasury and does not run its trains."
> 
> (I suggest you remove RhB when playing this variant - since it is rubbish!)

**Comment by ollybh** [comment]
> During stock rounds, the Robot always acts in 3rd position; it will acquire the most expensive private available (resolve ties by lowest number). It has no cash and never buys shares in Public Companies.

@ianwilson156: What happens if the robot can't afford the most expensive private available, but could afford cheaper ones? Does it pass, or buy the most expensive one it can afford?

**Comment by ianwilson156** [comment]
Robot has no cash. It "acquires" the private, not "buys" it. (In effect, it has unlimited funds to acquire privates and trains.)

**Comment by ollybh** [comment]
@ianwilson156 If the robot acquires both NOB and NB in the first stock round, then they will both close in the first operating round when their home hexes are laid. The SBB will place a token in Zürich when NB closes, but what happens when NOB closes. Does the general restriction on public companies not having two tokens in the same hex still apply?

**Comment by ianwilson156** [comment]
Yes, SBB is restricted to one token per hex like all companies, so - in the case you describe - it will not place a second token in Zurich (and therefore this slot will become available).
