### ISSUE TITLE
1807 map changes

### ISSUE THREAD

**Issue by ollybh** [ollybh/18xx#154]
As part of the redrawing of the map for production, a few minor changes are needed:
a) The impassable hexside NW of Ayr (F4) is removed.
b) The impassable hexside NW of Mumbles (U5) is removed.
c) The track in hex U9 is removed, and replaced with a off-map connection pointing towards Canterbury.
d) The port symbols in B12 & C13 are removed.

_Originally posted by @ianwilson156 in https://github.com/ollybh/18xx/issues/64#issuecomment-2482847350_

**Comment by ollybh** [comment]
> c) The track in hex U9 is removed, and replaced with a off-map connection pointing towards Canterbury.

@ianwilson156: I take it you mean hex U29 here (U9 is Rhondda). And do you mean that there is just a track stub in this hex, to allow Canterbury to be upgraded, but cannot be used by any trains?

**Comment by ollybh** [comment]
![image](https://github.com/user-attachments/assets/ab6ab434-35fd-4ae6-a732-e809f8989ff1)

**Comment by ollybh** [comment]
https://18xx.obsidiana.co.uk/map/18BF

**Comment by ianwilson156** [comment]
Yes, sorry, that was a typo - I meant U29 not U9.

**Comment by ollybh** [comment]
@ianwilson156: Does that updated map look correct?

**Comment by ianwilson156** [comment]
Yes, it looks ok.

**Comment by ollybh** [comment]
Updated map is in commit 1fab1d68e.
