### ISSUE TITLE
1807 updated tile manifest

### ISSUE THREAD

**Issue by ollybh** [ollybh/18xx#155]
Tile manifest from version 0.19 of the rules.

## Yellow

| Tile ID | Quantity | Upgrades |
| ---- | ---- | ---- |
| 3 | 4 | 87,88,204 |
| 4 | 12 | 87,88,204 |
| 5 | 6 | 14,15,619 |
| 6 | 6 | 14,15,619 |
| 7 | 6(U) | 18,21,22,26,27,28,29,30,31,624,625,626 |
| 8 | 30(U) | 16,17,19,21,22,23,24,25,28,29,30,31 |
| 9 | 34(U) | 18,19,20,23,24,26,27 |
| 57 | 6 | 14,15,619 |
| 58 | 10 | 87,88,204 |
| 201 | 4 | 207,208,622 |
| 202 | 4 | 207,208,622 |
| 621 | 4 | 207,208,622 |

## Green tiles

| Tile ID | Quantity | Upgrades |
| ---- | ---- | ---- |
| 14 | 4 | 63,611 |
| 15 | 10 | 63,611,448 |
| 16 | 2 | 43,70 |
| 17 | 2 | 47 |
| 18 | 2 | 43 |
| 19 | 2 | 45,46 |
| 20 | 2 | 44,47 |
| 21 | 1 | 46 |
| 22 | 1 | 45 |
| 23 | 8 | 41,43,45,47 |
| 24 | 8 | 42,43,46,47 |
| 25 | 4 | 40,45,46 |
| 26 | 2 | 42,44,45 |
| 27 | 2 | 41,44,46 |
| 28 | 2 | 39,43,46,70 |
| 29 | 2 | 39,43,45,70 |
| 30 | 1 | 42,70 |
| 31 | 1 | 41,70 |
| 87 | 5 | 911 |
| 88 | 5 | 911 |
| 204 | 5 | 911 |
| 207 | 6 | 216,623,801 |
| 208 | 4 | 216,623 |
| 619 | 4 | 63,611 |
| 622 | 4 | 216,623 |
| X1 | 2 | X7 |
| X4 | 2 | X6,X7 |
| X5 | 2 | X6 |
| X9 | 1 | X10 |
| X12 | 1 | X13 |

## Brown tiles

| Tile ID | Quantity | Upgrades |
| ---- | ---- | ---- |
| 39 | 2 | None |
| 40 | 2 | None |
| 41 | 2 | None |
| 42 | 2 | None |
| 43 | 2 | None |
| 44 | 2 | None |
| 45 | 2 | None |
| 46 | 2 | None |
| 47 | 2 | None |
| 63 | 5 | None |
| 70 | 1 | None |
| 216 | 2 | None |
| 448 | 3 | None |
| 611 | 2 | None |
| 623 | 4 | None |
| 801 | 3 | None |
| 911 | 3 | None |
| X6 | 3 | X14 |
| X7 | 3 | X14 |
| X10 | 1 | X11 |
| X13 | 1 | 49 |

## Grey tiles

| Tile ID | Quantity | Upgrades |
| ---- | ---- | ---- |
| 49 | 1 | None |
| X11 | 1 | None |
| X14 | 4 | None |

**Comment by ianwilson156** [comment]
Changes are:

Green:
#15 from 12 to 10
#21 from 2 to 1
#22 from 2 to 1
#25 from 6 to 4
#30 from 2 to 1
#31 from 2 to 1
#624, 625 & 626 - remove

Brown:
#63 from 6 to 5
#70 from 2 to 1
#448 from 8 to 3
#611 from 3 to 2
#911 from 5 to 2
