### ISSUE TITLE
1858: trading in privates (minor)

### ISSUE THREAD

**Issue by ianwilson156** [ollybh/18xx#16]
When starting a new company, you are given the option of "exchange <private> 50% for Treasury Share" which is not allowed. Clicking on that button just flags an error, but why not remove the button altogether? i.e. just have the "exchange <private> for 50% of President Share" button(s).

BTW, it's Director not President.

Also, when trading in a private for a treasury share it should be 100% not 50%.

**Comment by ollybh** [comment]
The '50%' on the buttons has been removed.

The spurious button suggesting that you can exchange a private for a treasury share in an unstarted public company is still there, for the moment. Just ignore it. It will get removed later.

Changing 'president' to 'director' might never happen. This description of the person who controls the company is hard-coded at multiple locations throughout the code base. It would be possible to change this so it could be overridden by each game, but I'm not sure it would be worth the effort.

**Comment by ianwilson156** [comment]
So we're stuck with President, ah well. I could make a comment about Americans, but I won't.

**Comment by ollybh** [comment]
The 'exchange for treasury share' button is removed in commit 1320f4c2c.
