### ISSUE TITLE
1858: order of track laying

### ISSUE THREAD

**Issue by ianwilson156** [ollybh/18xx#17]
You're going to hate me for this...

The order of track laying shouldn't affect the total cost!
As an example: the N built a yellow narrow gauge track from Valladolid to Madrid (though the mountain) for 40, then upgraded Valladolid to brown for 20, total cost 60. But doing it in the opposite order it costs 0 (upgrade) and 50 (40+10) for the yellow tile. It should cost 50 whichever order they are laid.
Might be tricky to code...

**Comment by ollybh** [comment]
That was working earlier – when the second tile is laid there's a check to see if either the first or second tile only added narrow gauge track, and then halves the cost of the second tile lay if one did. I must have broken this with some more recent changes.

**Comment by ollybh** [comment]
Fixed in commit 36aa9e9a5
