### ISSUE TITLE
1858: buying across counts as buying the 5th train

### ISSUE THREAD

**Issue by ianwilson156** [ollybh/18xx#18]
In my hotseat game, a company bought a 7E from another company, after four phase 7 trains had been bought from the bank, and this triggered the rusting of the 6H's. But it should be five _new_ trains that is the trigger.

**Comment by ollybh** [comment]
Good catch. That should be an easy one to fix.

**Comment by ollybh** [comment]
Fixed in commit 2ce199ac8
