### ISSUE TITLE
1858: cannot trade in O&V

### ISSUE THREAD

**Issue by ianwilson156** [ollybh/18xx#19]
In a SR, I traded in the S&C for a RP share, but it then wouldn't let me trade in the O&V (which was also connected by the same route). 
I could trade in the O&V into the N & W, both of whom were also connected.

**Comment by ollybh** [comment]
Just to check – how many shares in RP did you have when you were attempting to exchange O&V? You weren't already at 60%?

**Comment by ianwilson156** [comment]
I've spotted the issue - there were no treasury shares left to exchange! (All shares were in players hands or in the pool.)
So, the real bug is: cannot trade in a private for a pool share.

**Comment by ollybh** [comment]
Isn't that the correct behaviour? In a stock round you can only exchange a private for a treasury share.

You can exchange a private for a pool share in the private closure round, but the private closure round hasn't been implemented yet.

**Comment by ianwilson156** [comment]
Ooops! You are right, you can only exchange for a pool share in the FCR. Forgot about that, sorry. Item closed.
