### ISSUE TITLE
1858: illegal tile upgrade

### ISSUE THREAD

**Issue by ianwilson156** [ollybh/18xx#20]
The W, in west Madrid, was only connected to Murcia by a combination of broad and narrow gauge track. But the program allowed the upgrade (yellow to green). It also allowed the trade-in of the M&C i.e. the same error in the SR.

**Comment by ollybh** [comment]
Can you please send me the hotseat game JSON for this one?

**Comment by ianwilson156** [comment]
It won't let me paste a JSON here, nor does copying the game data into a gist file. I'll send you an email...

**Comment by ollybh** [comment]
Fixed in commit 06c1be2c5
