### ISSUE TITLE
Cities shared by two private railway companies need to show both names

### ISSUE THREAD

**Issue by ollybh** [ollybh/18xx#23]
Three cities (Sevilla, Córdoba and Zaragoza) are each home locations for two private railway companies. Each of these companies has an ability to reserve the city, but the user interface is not expecting this and so only shows the name of the last one declared. Both names need to be shown, though this is likely to require very small text.

**Comment by ianwilson156** [comment]
Yes, I spotted that as well. But to put both names in the circle would need unreadably small text.

The AAG map doesn't bother - in effect, it relies on the private railway graphic (small circles connected by lines) to show both reserved hexes and cities.

**Comment by ollybh** [comment]
Fixed in commits 94143f9389 / aa890b8bcf. These cities now start off showing both companies that are able to place a token.
