### ISSUE TITLE
1858: Cannot see value of Madrid in yellow (minor)

### ISSUE THREAD

**Issue by ianwilson156** [ollybh/18xx#26]
There's so much clutter on the Madrid hex (H11) that the (40) value is obscured. (The value of a run is correct.)

**Comment by ollybh** [comment]
There are quite a few problems like this. I've created issue #22 as a general reminder that the map needs to be de-cluttered.

**Comment by ollybh** [comment]
Fixed by commit 5ee3f3e45. The icons have been removed from city hexes as you can see the private name in the reserved city slot. This means you can now see the revenue of Madrid.
