### ISSUE TITLE
1858: major companies cannot upgrade home hexes of privates

### ISSUE THREAD

**Issue by ianwilson156** [ollybh/18xx#27]
TBF in Barcelona wanted to upgrade Valencia but couldn't, also A in Cordoba couldn't upgrade Cordoba! The restriction on laying in home hexes should only apply to yellow tiles.
[This was crippling for the A, since it had bought a 2M but now couldn't run it.]
P.S. The rule about laying yellow in the home hex of a private owned by the major is correct.

**Comment by ollybh** [comment]
Oops. I forgot to check whether the tile laid is yellow or an upgrade. This is fixed in commit 54e9deccc.
