### ISSUE TITLE
Private companies do not have descriptions

### ISSUE THREAD

**Issue by ollybh** [ollybh/18xx#36]
There are no `desc` properties defined for any of the private railway companies.

These should be added to all of them and show:

- Income (in yellow/green phases).
- Home hexes.
- Whether the private can be used to start a major (and where).

**Comment by ianwilson156** [comment]
It may also be useful to have the number: P1, P2 etc (as on the physical card), also listed in section 4.1 of the rules.

**Comment by ollybh** [comment]
Fixed in commit c98fe80fb.
