### ISSUE TITLE
1858: taking a token during final closure

### ISSUE THREAD

**Issue by ianwilson156** [ollybh/18xx#39]
If the major takes a token when absorbing a private during the final closure round, it says that it pays something. I'm not sure if it actually does pay it, but either way it should be free.

**Comment by ollybh** [comment]
This is basically the same as issue #9. It's when the private is exchanged for the company share that you get this message, rather than when the token is placed. This message is confusing, but the game behaviour is correct.

**Comment by ollybh** [comment]
No, this is nothing to do with issue #9.

**Comment by ollybh** [comment]
The tokens gained in the private closure round were being charged at twice the revenue of the city they were going in, as if these were tokens for newly started public companies. Fixed in commit 356bc8445.
