### ISSUE TITLE
1858: cannot take token in FCR

### ISSUE THREAD

**Issue by ianwilson156** [ollybh/18xx#41]
Testing 2p: in the Final Closure Round (after OR4.1), the O&V elected to take an RP treasury share. But the RP wasn't given the opportunity to place a token in Vigo.

Earlier in the round, the Z&P exchanged for a TBF treasury share and TBF took the token in Zaragoza.

I'll send you the JSON.

**Comment by ollybh** [comment]
This happened because O&V was the last private railway to operate in the private closure round. The round was finishing before the player was given a chance to place this token. A check has been added in commit dc2400155 to make sure that the round doesn't finish too early.
