### ISSUE TITLE
1858: cannot scrap train that has just been wounded

### ISSUE THREAD

**Issue by ianwilson156** [ollybh/18xx#42]
OR6.1 MZA had a wounded 4H plus an unwounded 6H. It scrapped the 4H and bought the first 7E, thus wounding its 6H. But it wasn't then allowed to scrap the 6H to buy another train (despite having the cash to do so).

I'll send you the JSON.

**Comment by ollybh** [comment]
Good catch. If a company bought a train that took them up to the train limit this was ending their train buying step, without checking to see if they owned any wounded trains that could be discarded. Fixed by commit c1cb6954f.
