### ISSUE TITLE
1858: order of discarding trains is wrong (minor)

### ISSUE THREAD

**Issue by ianwilson156** [ollybh/18xx#46]
When the first 6H/3M was bought, several companies had to discard a train. This should be in operating order, but it wasn't.

Same hotseat game as #45, at the end of OR3.1 (RP bought a 3M).

**Comment by ollybh** [comment]
I've changed the order of the companies to be operating order (commit a29ba18ac). However, discarding trains is kind of simultaneous – all companies over the train limit are listed, and anyone can choose to discard their trains first, regardless of the order that companies are listed.
