### ISSUE TITLE
1858: Final Private Exchange blocks token

### ISSUE THREAD

**Issue by Dave4B** [ollybh/18xx#47]
During Final Private Exchange if two companies which share a token slot have not been previously exchanged, e.g. C&M and C&S, and the tile is still yellow and has only one slot, the first company swapped in cannot lay a token because "no token slots available on G18". The second company is then allowed to place a token as the reservation has been removed. This should be first-come first-served.

**Comment by ianwilson156** [comment]
Good spot! Very much a corner case - extremely unlikely in practice, since the hex would usually have been upgraded to green by that stage.

**Comment by Dave4B** [comment]
I was testing 70%+ holdings after Forced Exchange, and that just happened! Sent from Mail for Windows From: ianwilson156Sent: 16 January 2023 10:01To: ollybh/18xxCc: Dave4B; AuthorSubject: Re: [ollybh/18xx] 1858: Final Private Exchange blocks token (Issue #47) Good spot! Very much a corner case - extremely unlikely in practice, since the hex would usually have been upgraded to green by that stage.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by ollybh** [comment]
@Dave4B Have you got a JSON file for this one?

**Comment by Dave4B** [comment]
Whilst recreating this, I seem to have discovered a related issue:
During SR 3 the TBF acquired the Z&P when there was no space Zaragosa for its token, but the program still went to the map and required the player to click on "Do not place station token", even though there was no other legal choice.
Should this just be skipped, as it is for companies which don't have a token slot?

For the present problem:
[hs_rvkuizhf_1674326173.json.txt](https://github.com/ollybh/18xx/files/10472857/hs_rvkuizhf_1674326173.json.txt)

**Comment by ollybh** [comment]
> Whilst recreating this, I seem to have discovered a related issue: During SR 3 the TBF acquired the Z&P when there was no space Zaragosa for its token, but the program still went to the map and required the player to click on "Do not place station token", even though there was no other legal choice. Should this just be skipped, as it is for companies which don't have a token slot?

I've created a separate issue for this, #51.

**Comment by ollybh** [comment]
This was a timing issue. The private closes before the tokening step, giving up its claim on the token slot. For these cities which are home to two privates, this meant the public company could be blocked out of the city if the other private hadn't yet closed.

Fixed in commit 7c60b9981.
