### ISSUE TITLE
1858: when taking a pool share in PCR, the private remains in players hand

### ISSUE THREAD

**Issue by ianwilson156** [ollybh/18xx#48]
Latest hotseat game: SJC swapped for a pool share of A. Everything was correct except the player didn't lose the private (it doesn't pay out, but does count towards share limit).

I'll send you the JSON in an email.

**Comment by ollybh** [comment]
Well spotted. I'd missed the step of deleting the private from the list of the companies owned by the player when swapping for a pool share. Fixed in commit 9a2b20d64.
