### ISSUE TITLE
1858: can acquire over gauge change

### ISSUE THREAD

**Issue by Dave4B** [ollybh/18xx#49]
A company acquired a private which was only connected via a mixed standard/meter gauge route, ie. an illegal one.
[1858_acquire.txt](https://github.com/ollybh/18xx/files/10461739/1858_acquire.txt)

**Comment by ollybh** [comment]
@Dave4B Can you please send the JSON file for that game? You get this by going to the tools page and clicking the download button in the game data section.

**Comment by Dave4B** [comment]
@ollybh I attached the transcript to the original report.
Unfortunately I have deleted the game, in order to keep things tidy.
I shall recreate the problem, and get back to you.

**Comment by Dave4B** [comment]
"We don't support that file type. Try again with ..."
Renamed it to .txt
[hs_fjzytovr_1674298700.json.txt](https://github.com/ollybh/18xx/files/10472051/hs_fjzytovr_1674298700.json.txt)

**Comment by ollybh** [comment]
Thanks. Reconstructing a game from the log is slow and error-prone, supplying the JSON file makes it much easier to examine the game state.

**Comment by ollybh** [comment]
Which acquisition is the problem? A acquiring CM&P? There's a narrow-gauge route from both of A's tokens to hex G12, which is one of CM&P's home hexes. There isn't a route from either of A's tokens to the Madrid station space, but this isn't needed, A can still take the token.

**Comment by Dave4B** [comment]
Good point!
It just LOOKS so wrong.
Please close as not-a-problem.

**Comment by ollybh** [comment]
What might help is keeping the private railway icons (the small yellow/green circles with the company initials) visible on top of tiles. At the moment they're hidden as soon as a tile is placed. If they could still be seen then connections to private railway home hexes might be more obvious. Once a private is converted or exchanged for a share all its icons could be removed.

**Comment by Dave4B** [comment]
@ollybh When a private is converted it still reserves the spaces so no-one else can build there until it is cashed in during the company's turn.
