### ISSUE TITLE
1858: SR1 doesn't end when all privates bought

### ISSUE THREAD

**Issue by ianwilson156** [ollybh/18xx#50]
Game #8 - all privates are purchased, there's nothing to do, but I have P85 left. I can't start a company, of course. So why don't we go to OR1 automatically?

**Comment by ollybh** [comment]
The code that was checking whether you could do anything in the stock round was seeing that you had enough money to start a public company using the SJ&C private, so wasn't passing automatically. Once it came to your next action you (correctly) weren't allowed to convert SJ&C as it was the first stock round, only pass.

Commit 084818acd fixes this by amending the checks with a test for the stock round number, so will now say you have no valid actions in this situation, and so automatically passes.
