### ISSUE TITLE
[1858] train + private income message misleading (enhancement)

### ISSUE THREAD

**Issue by Dave4B** [ollybh/18xx#57]
When a company has both Train and Private income, the Submit message is in the format
"Submit PtXXX train + PtYY private revenue"
The value XXX includes YY, but the message implies it is extra.
Reformatting it as
"Submit PtXXX (train + PtYY private) revenue"
would clear up this misunderstanding.

**Comment by ollybh** [comment]
D'oh. This did used to work, but I'd made some changes which meant a function that had only returned train revenue was also including the private revenue.

Fixed in commit f871c7f17.
