### ISSUE TITLE
18BF: P5 removed twice

### ISSUE THREAD

**Issue by Dave4B** [ollybh/18xx#58]
The three private railway companies removed from play are: P3 (Monkland and Kirkintilloch), P5 (Leicester and Swannington), P5 (Leicester and Swannington).
[hs_zemtukqo_1676117814.json.txt](https://github.com/ollybh/18xx/files/10713626/hs_zemtukqo_1676117814.json.txt)

**Comment by ollybh** [comment]
The randomisation code has been rewritten (commit bd6014c57) since this bug was raised. This duplication should not be possible any more.
