### ISSUE TITLE
18BF: Trains should not run to London without a token

### ISSUE THREAD

**Issue by Dave4B** [ollybh/18xx#60]
A company which does not have a token in a London station should not be able to run a train there.
[hs_zemtukqo_1676117814(2).json.txt](https://github.com/ollybh/18xx/files/10713699/hs_zemtukqo_1676117814.2.json.txt)

**Comment by ollybh** [comment]
@Dave4B There's no point testing 18BF at the moment, or reporting any bugs. I've not done much more than set up the map and the various companies. Anything beyond that is likely to be broken.

**Comment by ollybh** [comment]
Implemented in commit 15160877a.
