### ISSUE TITLE
2-player 1858: removed companies still appear on map

### ISSUE THREAD

**Issue by Dave4B** [ollybh/18xx#63]
The Z&P was removed at the start of the game, but still appears on the map instead of the M&Z.
[hs_dclzukhh_1676499182.json.txt](https://github.com/ollybh/18xx/files/10748416/hs_dclzukhh_1676499182.json.txt)

**Comment by ianwilson156** [comment]
That is what is supposed to happen - the companies are not removed from the game, just no available for sale. They still block building & tokening (until phase 5).

**Comment by Dave4B** [comment]
The rules of 1858 don't mention the 2-player game, so I can neither confirm nor deny this.

**Comment by ianwilson156** [comment]
We thought a 2-player variant would be helpful as a teaching/learning tool, so I made up some rules (based on the 1861 2p variant).

**Comment by Dave4B** [comment]
The rules link on the website doesn't include the 2 player variant. It probably should if this is going to be available.

**Comment by ollybh** [comment]
The 18xx.games wiki page for 1858 includes details of this variant: https://github.com/tobymao/18xx/wiki/1858.
