### ISSUE TITLE
1858: Private purchase failure

### ISSUE THREAD

**Issue by Dave4B** [ollybh/18xx#65]
3-player hot-seat game.
Player bids all remaining money on M&Z and others cannot afford to bid.
Message "undefined method private_closure_round" pops up, vanishes then the purchase doesn't happen.
json attached.
[hs_xxsifviw_1677702029.json.txt](https://github.com/ollybh/18xx/files/10865215/hs_xxsifviw_1677702029.json.txt)

**Comment by Dave4B** [comment]
Created the same problem when a player who has enough money to start an auction in the first stock round passes.
[hs_oknpsrzp_1677778365.json.txt](https://github.com/ollybh/18xx/files/10874767/hs_oknpsrzp_1677778365.json.txt)

**Comment by ollybh** [comment]
This will have me leaving the wrong code branch checked out. I'm still in the process of chopping the 1858 code into smaller chunks and getting them merged into the upstream codebase, if I forget to switch back to the master branch then you'll get weird errors like this.
