### ISSUE TITLE
Can place a token on unbuilt hexes when exchanging private for a share

### ISSUE THREAD

**Issue by ollybh** [ollybh/18xx#66]
In the first two operating rounds, A&S has built track in G4 and G6 to connect with M&V. It has not built anything in Santander. In the second stock round M&V is converted to a public company, and then A&S is exchanged for a share. The new public company is now allowed to place a token in Santander, even though there is not yet a tile on that hex.
![image](https://user-images.githubusercontent.com/11144854/228325351-5e150a77-f94f-4526-93e8-808d212d88eb.png)

The rules say (section 8.1):

> The Public Company may immediately place a station marker in a home hex of the Private Company, free of charge; the Company must have a spare station marker available and there must be space on the tile.

@ianwilson156 Is the space available if no tile has been placed on the hex? I would assume that this is illegal as there isn't a tile to have a space on, and so this is a bug, but can I get a ruling on this interpretation?

**Comment by ianwilson156** [comment]
The token placement is legal. Perhaps the rule should have said "... there must be space on the hex".
I've never had this come up in practice, since the tile has always been played beforehand, but clearly we need to define it for this implementation.

**Comment by ollybh** [comment]
Thanks for the clarification. This means the current behaviour is correct, so this is not a bug after all.
