### ISSUE TITLE
18Ardennes: Map issues

### ISSUE THREAD

**Issue by ianwilson156** [ollybh/18xx#76]
I've looked at the map and found the following:
1. The top row is B (not A)! This arose from changes done to the map during development.
2. There is no colouring of the cities to show which major they are associated with, but with rule enforcement it's probably unnecessary.
3. The port symbols should be on Vlissingen (correct), Brugge and Dunkerque.
4. There is no indication of N/S/E/W.
5. There are no indication of mines nor forts.
6. Vlissingen should have a W connection to E3.
7. The track stubs for M2/11/8/9/12/15 are missing.
8. There is a track stub for Dunkerque pointing NW, which applies when the tile is upgraded to green. This may be tricky to show/implement.

**Comment by ollybh** [comment]
Thanks for checking this. I've fixed the row letters and added the track stubs for Amsterdam/Paris/Frankfurt/the Ruhr (which I don't think I'd ever noticed when playing).

The rest of these are to be done later.

**Comment by ianwilson156** [comment]
You've missed the track stubs for Reims.

**Comment by ollybh** [comment]
So I had. These are now added.
