### ISSUE TITLE
18Ardennes: cannot par minor below 100

### ISSUE THREAD

**Issue by ianwilson156** [ollybh/18xx#79]
Hotseat game - initial auction, player 3 has only f95 and has the most. #5 and the Lux are left to buy. He can buy the Lux but cannot get #5 - error message "cannot par".

**Comment by ollybh** [comment]
D'oh. I'd tweaked a setting to stop major corporations from being parred in the stock rounds, and it had also stopped you from buying minors for less than 100F. Fixed now.
