### ISSUE TITLE
18Ardennes: fort bonus doubled but not connected to Paris

### ISSUE THREAD

**Issue by ianwilson156** [ollybh/18xx#80]
#7 is running with 3 forts but only connected to Strasbourg. It says f60 bonus, it should be only 30.

**Comment by Dave4B** [comment]
The opposite effect is also present - a company with forts connected to Paris but not Strasbourg and receives no bonus.

**Comment by ollybh** [comment]
Heh, that one was extra stupid. I had mistyped the hex address in the fort checks, and so it was looking for a connection to Basel (M27) instead of Paris (M7). Fixed now.
