### ISSUE TITLE
18Ardennes: minors can upgrade to brown

### ISSUE THREAD

**Issue by ianwilson156** [ollybh/18xx#82]
#10 upgrades The Ruhr to brown

**Comment by ollybh** [comment]
I had told you things would start going very wrong after the 4-trains came out! This rule hasn't been implemented yet. If you play on long enough, you'll also find that minors are able to buy 4D trains at the moment (and that the 4D trains don't run correctly).

**Comment by ollybh** [comment]
Fixed in commit b8299c22b.
