### ISSUE TITLE
18Ardennes: game won't reload

### ISSUE THREAD

**Issue by ianwilson156** [ollybh/18xx#84]
Hotseat game - trying to reload the game I get the following error message: (at the beginning or OR1.2)

We're sorry this game cannot be continued due to hex: undefined method `hex' for <Engine::Corporation: 14>
Broken action: { "type": "remove_token", "entity": "14", "entity_type": "corporation", "id": 109, "created_at": 1694343513, "city": "6-0-0", "slot": 0 }

**Comment by ollybh** [comment]
Sorry, I'd left some half-finished code checked out. Fixed now.
