### ISSUE TITLE
18Ardennes: can bid on major without nominating a minor

### ISSUE THREAD

**Issue by ianwilson156** [ollybh/18xx#88]
When bidding on a major in an auction round, a player must nominate an (eligible) minor to start it with, not just a sum of money.

P.S. Staatsiesenbahnen is misspelt (dark blue company), it should be Staatseisenbahnen.

**Comment by ollybh** [comment]
I've fixed the spelling of the Prussian railway, thanks for pointing out the mistake.

The major auction is still a work in progress. You now have to pick a minor when making a bid.
