### ISSUE TITLE
18Ardennes bidding thinks all Paris is both colours

### ISSUE THREAD

**Issue by Dave4B** [ollybh/18xx#89]
A company owning both M8 and M9 is allowed to bid on Nord with either.
East Paris and West Paris should be different colours.
A similar problem exists with l'Est.

**Comment by ollybh** [comment]
Oh yes, I'd forgotten that the city circles are different colours.

… except that the rules section on qualifying minor companies (5.2.1) tells that you should find the public companies qualifying cities in section 12.5 of the rules, or on the mini-maps on their charters. Section 12.5 says that Paris is a city for both the E and N, with no reference to the east or west circles.

Have you got a copy of the game? What do the mini-maps on the E and N charters show? Can we decide that everyone has always been playing this wrong?

**Comment by Dave4B** [comment]
I have a copy of version 0.2.36 May 2010 (print & play). I don't believe the charters have changed since.
The mini-map for l'Est shows the orange stations spots, including 9. The Nord shows brown including 8.
[18Ard-Charters.pdf](https://github.com/ollybh/18xx/files/12693343/18Ard-Charters.pdf)

**Comment by ollybh** [comment]
Fixed in commit a5b6e136f.
