### ISSUE TITLE
18Ardennes: Game crashes when operating minor companies

### ISSUE THREAD

**Issue by ianwilson156** [ollybh/18xx#98]
Got to the end of the minor auction, there's one minor left and one player with f60 - he should get it for 60 but it doesn't work.

**Comment by ollybh** [comment]
Grrr… that was working before. I must have broken it somehow.

**Comment by ianwilson156** [comment]
Yes, I thought so too.

**Comment by ollybh** [comment]
This was nothing to do with buying the minor for less than 100, that was still working correctly. The game was crashing when trying to operate the first minor company, I'd managed to break this when implementing major companies growing up.
Fixed in commit d0ba9fc74.
